dataset:
  robot_type: "franka_task_space"
  fps: 20
  chunks_size: 1000

modality_template_path: "./demos/franka_mimicgen/config/modality_task_space.json"
info_template_path: "./demos/franka_mimicgen/config/info.json"

tasks:
  0: "Pick up the red cube and put it onto the blue cube. Pick up the green cube and place it onto the red cube."
  1: "valid"

# Mapping from HDF5 keys to LeRobot keys
# Each entry in 'state' and 'action' is a list of sources to be concatenated
mapping:
  state:
    # - key: "obs.eef_pos"
    #   slice: "[:-1]"
    # - key: "obs.eef_quat"
    #   slice: "[:-1]"
    # - key: "obs.gripper_pos"
    #   slice: "[:-1, 0]"
    #   reshape: [-1, 1]
    - key: "obs.eef_pos"
      slice: [[null, -1]]
    - key: "obs.eef_quat"
      slice: [[null, -1]]
    - key: "obs.gripper_pos"
      slice: [[null, -1], 0]
      reshape: [-1, 1]
  
  action:
    - key: "actions"
      slice: [[null, -1], [null, -1]]
    - key: "obs.gripper_pos"
      slice: [[1, null], 0]
      reshape: [-1, 1]

# Mapping from LeRobot video keys to file suffixes
video_mapping:
  # "observation.images.ego_view": "ego_rgb"
  # "observation.images.left_view": "left_wrist_rgb"
  # "observation.images.right_view": "right_wrist_rgb"
  "observation.images.table_view": "table_rgb"

# LeRobot specific keys
lerobot_keys:
  state: "observation.state"
  action: "action"
  annotation: 
    - "annotation.human.action.task_description"
    - "annotation.human.action.valid"